# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: frontend-service
# spec:
#   selector:
#     app: react-client
#   ports:
#     - protocol: TCP
#       port: 3000
#       targetPort: 80
#   type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-nodeport-service
spec:
  selector:
    app: react-client
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 80
      nodePort: 30030  # Optional: Choose a port between 30000-32767
  type: NodePort


---
# apiVersion: v1
# kind: Service
# metadata:
#   name: frontend-app-service
# spec:
#   selector:
#     app: react-client
#   ports:
#     - protocol: TCP
#       port: 3000
#       targetPort: 80