# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: kafka-ui-service
#   namespace: kafka
# spec:
#   selector:
#     app: kafka-ui
#   ports:
#     - protocol: TCP
#       port: 8091
#       targetPort: 8080
#   type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: kafka-ui-nodeport-service
  namespace: kafka
spec:
  selector:
    app: kafka-ui
  ports:
    - protocol: TCP
      port: 8091
      targetPort: 8080
      nodePort: 30891  # Optional: Choose a port between 30000-32767
  type: NodePort