---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  namespace: kafka
spec:
  selector:
    app: kafka
  ports:
    - protocol: TCP
      port: 29092
      targetPort: 29092

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: kafka-adv-service
#   namespace: kafka
# spec:
#   selector:
#     app: kafka
#   ports:
#     - protocol: TCP
#       port: 9092         # Internal Cluster Port
#       targetPort: 9092   # Kafka Container Port
#       nodePort: 30092    # External NodePort
#   type: NodePort