# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: trans-service
# spec:
#   selector:
#     app: ligo-server-trans
#   ports:
#     - protocol: TCP
#       port: 8089
#       targetPort: 8088

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: trans-lb-service
# spec:
#   selector:
#     app: ligo-server-trans
#   ports:
#     - protocol: TCP
#       port: 8089
#       targetPort: 8088
#   type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: trans-nodeport-service
spec:
  selector:
    app: ligo-server-trans
  ports:
    - protocol: TCP
      port: 8089
      targetPort: 8088
      nodePort: 30889  # Optional: Choose a port between 30000-32767
  type: NodePort