apiVersion: v1
kind: Secret
metadata:
  name: groq-api-secret
type: Opaque
data:
  GROQ_API_KEY: QmVhcmVyIGdza19nYTdIM0lGZGx5a3E2NEt6ZjMxRFdHZHliM0ZZcUkxdTlCNWlkM1lKbzE1QmI2ODlwWk5M
  GROQ_API_URL: aHR0cHM6Ly9hcGkuZ3JvcS5jb20vb3BlbmFpL3YxL2NoYXQvY29tcGxldGlvbnM=