apiVersion: apps/v1
kind: Deployment
metadata:
  name: ligo-server-chat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ligo-server-chat
  template:
    metadata:
      labels:
        app: ligo-server-chat
    spec:
      containers:
        - name: ligo-server-chat
          image: hoanganh26/ligo-server-chat
          ports:
            - containerPort: 8083
          # resource request limit
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "900m"
              memory: "1Gi"
          env:
            - name: FRONTEND_URI
              valueFrom:
                configMapKeyRef:
                  name: chat-config
                  key: FRONTEND_URI
            - name: KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: chat-config
                  key: KAFKA_BOOTSTRAP_SERVERS

